bookwyrm/urls.py
""" url routing for the app and api """
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from bookwyrm import settings, views
from bookwyrm.utils import regex

user_path = r"^user/(?P<username>%s)" % regex.username
local_user_path = r"^user/(?P<username>%s)" % regex.localname

status_types = [
    "status",
    "review",
    "reviewrating",
    "comment",
    "quotation",
    "boost",
    "generatednote",
]
status_path = r"%s/(%s)/(?P<status_id>\d+)" % (user_path, "|".join(status_types))

book_path = r"^book/(?P<book_id>\d+)"

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # federation endpoints
    re_path(r"^inbox/?$", views.Inbox.as_view()),
    re_path(r"%s/inbox/?$" % local_user_path, views.Inbox.as_view()),
    re_path(r"%s/outbox/?$" % local_user_path, views.Outbox.as_view()),
    re_path(r"^\.well-known/webfinger/?$", views.webfinger),
    re_path(r"^\.well-known/nodeinfo/?$", views.nodeinfo_pointer),
    re_path(r"^\.well-known/host-meta/?$", views.host_meta),
    re_path(r"^nodeinfo/2\.0/?$", views.nodeinfo),
    re_path(r"^api/v1/instance/?$", views.instance_info),
    re_path(r"^api/v1/instance/peers/?$", views.peers),
    # polling updates
    re_path("^api/updates/notifications/?$", views.get_notification_count),
    re_path("^api/updates/stream/(?P<stream>[a-z]+)/?$", views.get_unread_status_count),
    # authentication
    re_path(r"^login/?$", views.Login.as_view()),
    re_path(r"^register/?$", views.Register.as_view()),
    re_path(r"^logout/?$", views.Logout.as_view()),
    re_path(r"^password-reset/?$", views.PasswordResetRequest.as_view()),
    re_path(
        r"^password-reset/(?P<code>[A-Za-z0-9]+)/?$", views.PasswordReset.as_view()
    ),
    # admin
    re_path(r"^settings/site-settings/?$", views.Site.as_view(), name="settings-site"),
    re_path(
        r"^settings/email-preview/?$",
        views.site.email_preview,
        name="settings-email-preview",
    ),
    re_path(
        r"^settings/users/?$", views.UserAdminList.as_view(), name="settings-users"
    ),
    re_path(
        r"^settings/users/(?P<user>\d+)/?$",
        views.UserAdmin.as_view(),
        name="settings-user",
    ),
    re_path(
        r"^settings/federation/?$",
        views.Federation.as_view(),
        name="settings-federation",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/?$",
        views.FederatedServer.as_view(),
        name="settings-federated-server",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/block?$",
        views.federation.block_server,
        name="settings-federated-server-block",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/unblock?$",
        views.federation.unblock_server,
        name="settings-federated-server-unblock",
    ),
    re_path(
        r"^settings/federation/add/?$",
        views.AddFederatedServer.as_view(),
        name="settings-add-federated-server",
    ),
    re_path(
        r"^settings/federation/import/?$",
        views.ImportServerBlocklist.as_view(),
        name="settings-import-blocklist",
    ),
    re_path(
        r"^settings/invites/?$", views.ManageInvites.as_view(), name="settings-invites"
    ),
    re_path(
        r"^settings/requests/?$",
        views.ManageInviteRequests.as_view(),
        name="settings-invite-requests",
    ),
    re_path(
        r"^settings/requests/ignore?$",
        views.ignore_invite_request,
        name="settings-invite-requests-ignore",
    ),
    re_path(
        r"^invite-request/?$", views.InviteRequest.as_view(), name="invite-request"
    ),
    re_path(r"^invite/(?P<code>[A-Za-z0-9]+)/?$", views.Invite.as_view()),
    # moderation
    re_path(r"^settings/reports/?$", views.Reports.as_view(), name="settings-reports"),
    re_path(
        r"^settings/reports/(?P<report_id>\d+)/?$",
        views.Report.as_view(),
        name="settings-report",
    ),
    re_path(
        r"^settings/reports/(?P<user_id>\d+)/suspend/?$",
        views.suspend_user,
        name="settings-report-suspend",
    ),
    re_path(
        r"^settings/reports/(?P<report_id>\d+)/resolve/?$",
        views.resolve_report,
        name="settings-report-resolve",
    ),
    re_path(r"^report/?$", views.make_report, name="report"),
    # landing pages
    re_path(r"^about/?$", views.About.as_view(), name="about"),
    path("", views.Home.as_view(), name="landing"),
    re_path(r"^discover/?$", views.Discover.as_view()),
    re_path(r"^notifications/?$", views.Notifications.as_view()),
    re_path(r"^directory/?", views.Directory.as_view(), name="directory"),
    # Get started
    re_path(
        r"^get-started/profile/?$",
        views.GetStartedProfile.as_view(),
        name="get-started-profile",
    ),
    re_path(
        r"^get-started/books/?$",
        views.GetStartedBooks.as_view(),
        name="get-started-books",
    ),
    re_path(
        r"^get-started/users/?$",
        views.GetStartedUsers.as_view(),
        name="get-started-users",
    ),
    # feeds
    re_path(r"^(?P<tab>home|local|federated)/?$", views.Feed.as_view()),
    re_path(
        r"^direct-messages/?$", views.DirectMessage.as_view(), name="direct-messages"
    ),
    re_path(
        r"^direct-messages/(?P<username>%s)?$" % regex.username,
        views.DirectMessage.as_view(),
        name="direct-messages-user",
    ),
    # search
    re_path(r"^search/?$", views.Search.as_view()),
    # imports
    re_path(r"^import/?$", views.Import.as_view()),
    re_path(r"^import/(\d+)/?$", views.ImportStatus.as_view()),
    # users
    re_path(r"%s/?$" % user_path, views.User.as_view(), name="user-feed"),
    re_path(r"%s\.json$" % user_path, views.User.as_view()),
    re_path(r"%s/rss" % user_path, views.rss_feed.RssFeed(), name="user-rss"),
    re_path(
        r"%s/followers(.json)?/?$" % user_path,
        views.Followers.as_view(),
        name="user-followers",
    ),
    re_path(
        r"%s/following(.json)?/?$" % user_path,
        views.Following.as_view(),
        name="user-following",
    ),
    # lists
    re_path(r"%s/lists/?$" % user_path, views.UserLists.as_view(), name="user-lists"),
    re_path(r"^list/?$", views.Lists.as_view(), name="lists"),
    re_path(r"^list/(?P<list_id>\d+)(.json)?/?$", views.List.as_view(), name="list"),
    re_path(r"^list/add-book/?$", views.list.add_book, name="list-add-book"),
    re_path(
        r"^list/(?P<list_id>\d+)/remove/?$",
        views.list.remove_book,
        name="list-remove-book",
    ),
    re_path(
        r"^list-item/(?P<list_item_id>\d+)/set-position$",
        views.list.set_book_position,
        name="list-set-book-position",
    ),
    re_path(
        r"^list/(?P<list_id>\d+)/curate/?$", views.Curate.as_view(), name="list-curate"
    ),
    # Uyser books
    re_path(r"%s/books/?$" % user_path, views.Shelf.as_view(), name="user-shelves"),
    re_path(
        r"^%s/(helf|books)/(?P<shelf_identifier>[\w-]+)(.json)?/?$" % user_path,
        views.Shelf.as_view(),
        name="shelf",
    ),
    re_path(
        r"^%s/(books|shelf)/(?P<shelf_identifier>[\w-]+)(.json)?/?$" % local_user_path,
        views.Shelf.as_view(),
        name="shelf",
    ),
    re_path(r"^create-shelf/?$", views.create_shelf, name="shelf-create"),
    re_path(r"^delete-shelf/(?P<shelf_id>\d+)?$", views.delete_shelf),
    re_path(r"^shelve/?$", views.shelve),
    re_path(r"^unshelve/?$", views.unshelve),
    # goals
    re_path(
        r"%s/goal/(?P<year>\d{4})/?$" % user_path,
        views.Goal.as_view(),
        name="user-goal",
    ),
    re_path(r"^hide-goal/?$", views.hide_goal, name="hide-goal"),
    # preferences
    re_path(r"^preferences/profile/?$", views.EditUser.as_view(), name="prefs-profile"),
    re_path(r"^preferences/password/?$", views.ChangePassword.as_view()),
    re_path(r"^preferences/block/?$", views.Block.as_view()),
    re_path(r"^block/(?P<user_id>\d+)/?$", views.Block.as_view()),
    re_path(r"^unblock/(?P<user_id>\d+)/?$", views.unblock),
    # statuses
    re_path(r"%s(.json)?/?$" % status_path, views.Status.as_view(), name="status"),
    re_path(r"%s/activity/?$" % status_path, views.Status.as_view(), name="status"),
    re_path(
        r"%s/replies(.json)?/?$" % status_path, views.Replies.as_view(), name="replies"
    ),
    re_path(
        r"^post/?$",
        views.CreateStatus.as_view(),
        name="create-status",
    ),
    re_path(
        r"^post/(?P<status_type>\w+)/?$",
        views.CreateStatus.as_view(),
        name="create-status",
    ),
    re_path(
        r"^delete-status/(?P<status_id>\d+)/?$",
        views.DeleteStatus.as_view(),
        name="delete-status",
    ),
    re_path(
        r"^redraft-status/(?P<status_id>\d+)/?$",
        views.DeleteAndRedraft.as_view(),
        name="redraft",
    ),
    # interact
    re_path(r"^favorite/(?P<status_id>\d+)/?$", views.Favorite.as_view()),
    re_path(r"^unfavorite/(?P<status_id>\d+)/?$", views.Unfavorite.as_view()),
    re_path(r"^boost/(?P<status_id>\d+)/?$", views.Boost.as_view()),
    re_path(r"^unboost/(?P<status_id>\d+)/?$", views.Unboost.as_view()),
    # books
    re_path(r"%s(.json)?/?$" % book_path, views.Book.as_view()),
    re_path(r"%s/edit/?$" % book_path, views.EditBook.as_view()),
    re_path(r"%s/confirm/?$" % book_path, views.ConfirmEditBook.as_view()),
    re_path(r"^create-book/?$", views.EditBook.as_view()),
    re_path(r"^create-book/confirm?$", views.ConfirmEditBook.as_view()),
    re_path(r"%s/editions(.json)?/?$" % book_path, views.Editions.as_view()),
    re_path(
        r"^upload-cover/(?P<book_id>\d+)/?$", views.upload_cover, name="upload-cover"
    ),
    re_path(r"^add-description/(?P<book_id>\d+)/?$", views.add_description),

celerywyrm/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path

from celerywyrm import settings

urlpatterns = [
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookwyrm/models/attachment.py
""" media that is posted in the app """
from django.db import models

from bookwyrm import activitypub
from .activitypub_mixin import ActivitypubMixin
from .base_model import BookWyrmModel
from . import fields


class Attachment(ActivitypubMixin, BookWyrmModel):
    """ an image (or, in the future, video etc) associated with a status """

    status = models.ForeignKey(
        "Status", on_delete=models.CASCADE, related_name="attachments", null=True
    )
    reverse_unfurl = True

    class Meta:
        """ one day we'll have other types of attachments besides images """

        abstract = True


class Image(Attachment):
    """ an image attachment """

    image = fields.ImageField(
        upload_to="status/",
        null=True,
        blank=True,
        activitypub_field="url",
        alt_field="caption",
    )
    caption = fields.TextField(null=True, blank=True, activitypub_field="name")

    activity_serializer = activitypub.Document

bookwyrm/models/author.py
""" database schema for info about authors """
from django.db import models

from bookwyrm import activitypub
from bookwyrm.settings import DOMAIN

from .book import BookDataModel
from . import fields


class Author(BookDataModel):
    """ basic biographic info """

    wikipedia_link = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    # idk probably other keys would be useful here?
    born = fields.DateTimeField(blank=True, null=True)
    died = fields.DateTimeField(blank=True, null=True)
    name = fields.CharField(max_length=255, deduplication_field=True)
    aliases = fields.ArrayField(
        models.CharField(max_length=255), blank=True, default=list
    )
    bio = fields.HtmlField(null=True, blank=True)

    def get_remote_id(self):
        """ editions and works both use "book" instead of model_name """
        return "https://%s/author/%s" % (DOMAIN, self.id)

    activity_serializer = activitypub.Author

bookwyrm/models/connector.py
""" manages interfaces with external sources of book data """
from django.db import models
from bookwyrm.connectors.settings import CONNECTORS

from .base_model import BookWyrmModel


ConnectorFiles = models.TextChoices("ConnectorFiles", CONNECTORS)


class Connector(BookWyrmModel):
    """ book data source connectors """

    identifier = models.CharField(max_length=255, unique=True)
    priority = models.IntegerField(default=2)
    name = models.CharField(max_length=255, null=True, blank=True)
    local = models.BooleanField(default=False)
    connector_file = models.CharField(max_length=255, choices=ConnectorFiles.choices)
    api_key = models.CharField(max_length=255, null=True, blank=True)

    base_url = models.CharField(max_length=255)
    books_url = models.CharField(max_length=255)
    covers_url = models.CharField(max_length=255)
    search_url = models.CharField(max_length=255, null=True, blank=True)
    isbn_search_url = models.CharField(max_length=255, null=True, blank=True)

    politeness_delay = models.IntegerField(null=True, blank=True)  # seconds
    max_query_count = models.IntegerField(null=True, blank=True)
    # how many queries executed in a unit of time, like a day
    query_count = models.IntegerField(default=0)
    # when to reset the query count back to 0 (ie, after 1 day)
    query_count_expiry = models.DateTimeField(auto_now_add=True, blank=True)

    class Meta:
        """ check that there's code to actually use this connector """

        constraints = [
            models.CheckConstraint(
                check=models.Q(connector_file__in=ConnectorFiles),
                name="connector_file_valid",
            )
        ]

    def __str__(self):
        return "{} ({})".format(
            self.identifier,
            self.id,
        )

bookwyrm/models/favorite.py
""" like/fav/star a status """
from django.apps import apps
from django.db import models
from django.utils import timezone

from bookwyrm import activitypub
from .activitypub_mixin import ActivityMixin
from .base_model import BookWyrmModel
from . import fields
from .status import Status


class Favorite(ActivityMixin, BookWyrmModel):
    """ fav'ing a post """

    user = fields.ForeignKey(
        "User", on_delete=models.PROTECT, activitypub_field="actor"
    )
    status = fields.ForeignKey(
        "Status", on_delete=models.PROTECT, activitypub_field="object"
    )

    activity_serializer = activitypub.Like

    @classmethod
    def ignore_activity(cls, activity):
        """ don't bother with incoming favs of unknown statuses """
        return not Status.objects.filter(remote_id=activity.object).exists()

    def save(self, *args, **kwargs):
        """ update user active time """
        self.user.last_active_date = timezone.now()
        self.user.save(broadcast=False)
        super().save(*args, **kwargs)

        if self.status.user.local and self.status.user != self.user:
            notification_model = apps.get_model(
                "bookwyrm.Notification", require_ready=True
            )
            notification_model.objects.create(
                user=self.status.user,
                notification_type="FAVORITE",
                related_user=self.user,
                related_status=self.status,
            )

    def delete(self, *args, **kwargs):
        """ delete and delete notifications """
        # check for notification
        if self.status.user.local:
            notification_model = apps.get_model(
                "bookwyrm.Notification", require_ready=True
            )
            notification = notification_model.objects.filter(
                user=self.status.user,
                related_user=self.user,
                related_status=self.status,
                notification_type="FAVORITE",
            ).first()
            if notification:
                notification.delete()
        super().delete(*args, **kwargs)

    class Meta:
        """ can't fav things twice """

        unique_together = ("user", "status")

bookwyrm/models/federated_server.py
""" connections to external ActivityPub servers """
from urllib.parse import urlparse
from django.db import models
from .base_model import BookWyrmModel

FederationStatus = models.TextChoices(
    "Status",
    [
        "federated",
        "blocked",
    ],
)


class FederatedServer(BookWyrmModel):
    """ store which servers we federate with """

    server_name = models.CharField(max_length=255, unique=True)
    status = models.CharField(
        max_length=255, default="federated", choices=FederationStatus.choices
    )
    # is it mastodon, bookwyrm, etc
    application_type = models.CharField(max_length=255, null=True, blank=True)
    application_version = models.CharField(max_length=255, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    def block(self):
        """ block a server """
        self.status = "blocked"
        self.save()

        # deactivate all associated users
        self.user_set.filter(is_active=True).update(
            is_active=False, deactivation_reason="domain_block"
        )

    def unblock(self):
        """ unblock a server """
        self.status = "federated"
        self.save()

        self.user_set.filter(deactivation_reason="domain_block").update(
            is_active=True, deactivation_reason=None
        )

    @classmethod
    def is_blocked(cls, url):
        """ look up if a domain is blocked """
        url = urlparse(url)
        domain = url.netloc
        return cls.objects.filter(server_name=domain, status="blocked").exists()

bookwyrm/templates/settings/admin_layout.html
{% extends 'layout.html' %}
{% load i18n %}

{% block title %}{% trans "Administration" %}{% endblock %}

{% block content %}

<header class="block column is-offset-one-quarter pl-1">
    <div class="columns is-mobile">
        <div class="column">
            <h1 class="title">{% block header %}{% endblock %}</h1>
        </div>
        <div class="column is-narrow">
            {% block edit-button %}{% endblock %}
        </div>
    </div>
</header>

<div class="block columns">
    <nav class="menu column is-one-quarter">
        {% if perms.bookwyrm.create_invites %}
        <h2 class="menu-label">{% trans "Manage Users" %}</h2>
        <ul class="menu-list">
            <li>
                {% url 'settings-users' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Users" %}</a>
            </li>
            <li>
                {% url 'settings-invite-requests' as url %}
                {% url 'settings-invites' as alt_url %}
                <a href="{{ url }}"{% if url in request.path or request.path in alt_url %} class="is-active" aria-selected="true"{% endif %}>{% trans "Invites" %}</a>
            </li>
            <li>
                {% url 'settings-reports' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Reports" %}</a>
            </li>
            <li>
                {% url 'settings-federation' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Federated Servers" %}</a>
            </li>
        </ul>
        {% endif %}
        {% if perms.bookwyrm.edit_instance_settings %}
        <h2 class="menu-label">{% trans "Instance Settings" %}</h2>
        <ul class="menu-list">
            <li>
                {% url 'settings-site' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Site Settings" %}</a>
                {% if url in request.path %}
                <ul class="emnu-list">
                    <li><a href="{{ url }}#instance-info">{% trans "Instance Info" %}</a></li>
                    <li><a href="{{ url }}#images">{% trans "Images" %}</a></li>
                    <li><a href="{{ url }}#footer">{% trans "Footer Content" %}</a></li>
                    <li><a href="{{ url }}#registration">{% trans "Registration" %}</a></li>
                </ul>
                {% endif %}
            </li>
        </ul>
        {% endif %}
    </nav>
    <div class="column">
        {% block panel %}{% endblock %}
    </div>
</div>

{% endblock %}

bookwyrm/templates/settings/edit_server.html
{% extends 'settings/admin_layout.html' %}
{% load i18n %}
{% block title %}{% trans "Add server" %}{% endblock %}

{% block header %}
{% trans "Add server" %}
<a href="{% url 'settings-federation' %}" class="has-text-weight-normal help">{% trans "Back to server list" %}</a>
{% endblock %}

{% block panel %}

<div class="tabs">
    <ul>
        {% url 'settings-import-blocklist' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Import block list" %}</a>
        </li>
        {% url 'settings-add-federated-server' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Add server" %}</a>
        </li>
    </ul>
</div>

<form method="POST" action="{% url 'settings-add-federated-server' %}">
    {% csrf_token %}
    <div class="columns">
        <div class="column is-half">
            <div>
                <label class="label" for="id_server_name">{% trans "Instance:" %}</label>
                <input type="text" name="server_name" maxlength="255" class="input" required id="id_server_name" value="{{ form.server_name.value|default:'' }}" placeholder="domain.com">
                {% for error in form.server_name.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
            <div>
                <label class="label" for="id_status">{% trans "Status:" %}</label>
                <div class="select">
                    <select name="status" class="" id="id_status">
                        <option value="federated" {% if form.status.value == "federated" %}selected=""{% endif %}>{% trans "Federated" %}</option>
                        <option value="blocked" {% if form.status.value == "blocked" or not form.status.value %}selected{% endif %}>{% trans "Blocked" %}</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="column is-half">
            <div>
                <label class="label" for="id_application_type">{% trans "Software:" %}</label>
                <input type="text" name="application_type" maxlength="255" class="input" id="id_application_type" value="{{ form.application_type.value|default:'' }}">
                {% for error in form.application_type.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
            <div>
                <label class="label" for="id_application_version">{% trans "Version:" %}</label>
                <input type="text" name="application_version" maxlength="255" class="input" id="id_application_version" value="{{ form.application_version.value|default:'' }}">
                {% for error in form.application_version.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <p>
        <label class="label" for="id_notes">{% trans "Notes:" %}</label>
        <textarea name="notes" cols="None" rows="None" class="textarea" id="id_notes">{{ form.notes.value|default:'' }}</textarea>
    </p>

    <button type="submit" class="button is-primary">{% trans "Save" %}</button>
</form>

{% endblock %}

bookwyrm/templates/settings/federated_server.html
{% extends 'settings/admin_layout.html' %}
{% block title %}{{ server.server_name }}{% endblock %}
{% load i18n %}
{% load bookwyrm_tags %}

{% block header %}
{{ server.server_name }}

{% if server.status == "blocked" %}<span class="icon icon-x has-text-danger is-size-5" title="{% trans 'Blocked' %}"><span class="is-sr-only">{% trans "Blocked" %}</span></span>
{% endif %}

<a href="{% url 'settings-federation' %}" class="has-text-weight-normal help">{% trans "Back to server list" %}</a>
{% endblock %}

{% block panel %}
<div class="columns">
    <section class="column is-half content">
        <h2 class="title is-4">{% trans "Details" %}</h2>
        <dl>
            <div class="is-flex">
                <dt>{% trans "Software:" %}</dt>
                <dd>{{ server.application_type }}</dd>
            </div>
            <div class="is-flex">
                <dt>{% trans "Version:" %}</dt>
                <dd>{{ server.application_version }}</dd>
            </div>
            <div class="is-flex">
                <dt>{% trans "Status:" %}</dt>
                <dd>{{ server.status }}</dd>
            </div>
        </dl>
    </section>

    <section class="column is-half content">
        <h2 class="title is-4">{% trans "Activity" %}</h2>
        <dl>
            <div class="is-flex">
                <dt>{% trans "Users:" %}</dt>
                <dd>
                    {{ users.count }}
                    {% if server.user_set.count %}(<a href="{% url 'settings-users' %}?server={{ server.server_name }}">{% trans "View all" %}</a>){% endif %}
                </dd>
            </div>
            <div class="is-flex">
                <dt>{% trans "Reports:" %}</dt>
                <dd>
                    {{ reports.count }}
                    {% if reports.count %}(<a href="{% url 'settings-reports' %}?server={{ server.server_name }}">{% trans "View all" %}</a>){% endif %}
                </dd>
            </div>
            <div class="is-flex">
                <dt>{% trans "Followed by us:" %}</dt>
                <dd>
                    {{ followed_by_us.count }}
                </dd>
            </div>
            <div class="is-flex">
                <dt>{% trans "Followed by them:" %}</dt>
                <dd>
                    {{ followed_by_them.count }}
                </dd>
            </div>
            <div class="is-flex">
                <dt>{% trans "Blocked by us:" %}</dt>
                <dd>
                    {{ blocked_by_us.count }}
                </dd>
            </div>
        </dl>
    </section>
</div>

<section class="block content">
    <header class="columns is-mobile">
        <div class="column">
            <h2 class="title is-4 mb-0">{% trans "Notes" %}</h2>
        </div>
        <div class="column is-narrow">
            {% trans "Edit" as button_text %}
            {% include 'snippets/toggle/open_button.html' with text=button_text icon="pencil" controls_text="edit-notes" %}
        </div>
    </header>
    {% if server.notes %}
    <p id="hide-edit-notes">{{ server.notes|to_markdown|safe }}</p>
    {% endif %}
    <form class="box is-hidden" method="POST" action="{% url 'settings-federated-server' server.id %}" id="edit-notes">
        {% csrf_token %}
        <p>
            <label class="is-sr-only" for="id_notes">Notes:</label>
            <textarea name="notes" cols="None" rows="None" class="textarea" id="id_notes">{{ server.notes|default:"" }}</textarea>
        </p>
        <button type="submit" class="button is-primary">{% trans "Save" %}</button>
        {% trans "Cancel" as button_text %}
        {% include 'snippets/toggle/close_button.html' with text=button_text controls_text="edit-notes" %}
    </form>
</section>

<section class="block content">
    <h2 class="title is-4">{% trans "Actions" %}</h2>
    {% if server.status != 'blocked' %}
    <form class="block" method="post" action="{% url 'settings-federated-server-block' server.id %}">
        {% csrf_token %}
        <button class="button is-danger">{% trans "Block" %}</button>
        <p class="help">{% trans "All users from this instance will be deactivated." %}</p>
    </form>
    {% else %}
    <form class="block" method="post" action="{% url 'settings-federated-server-unblock' server.id %}">
        {% csrf_token %}
        <button class="button">{% trans "Un-block" %}</button>
        <p class="help">{% trans "All users from this instance will be re-activated." %}</p>
    </form>
    {% endif %}
</section>

{% endblock %}

bookwyrm/templates/settings/invite_request_filters.html
{% extends 'snippets/filters_panel/filters_panel.html' %}

{% block filter_fields %}
{% include 'settings/status_filter.html' %}
{% endblock %}

bookwyrm/templates/settings/user_admin_filters.html
{% extends 'snippets/filters_panel/filters_panel.html' %}

{% block filter_fields %}
{% include 'settings/server_filter.html' %}
{% include 'settings/username_filter.html' %}
{% endblock %}